// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIrjMlcNJgEBurd2YawSKnU_CxkeSY-JE',
    appId: '1:769280217055:web:4829f862d0370e3c54fe6a',
    messagingSenderId: '769280217055',
    projectId: 'safe-return2',
    authDomain: 'safe-return2.firebaseapp.com',
    storageBucket: 'safe-return2.appspot.com',
    measurementId: 'G-GQNG0D96W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJFu3f44BBM-nt3Gra0o8JYdZKzPuzdps',
    appId: '1:769280217055:android:96d343d7532eaeed54fe6a',
    messagingSenderId: '769280217055',
    projectId: 'safe-return2',
    storageBucket: 'safe-return2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wuNIJJBD66IraXKdNebZy6UvjDQBzYY',
    appId: '1:769280217055:ios:ae5e6d537e15e94054fe6a',
    messagingSenderId: '769280217055',
    projectId: 'safe-return2',
    storageBucket: 'safe-return2.appspot.com',
    iosBundleId: 'com.example.safeReturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wuNIJJBD66IraXKdNebZy6UvjDQBzYY',
    appId: '1:769280217055:ios:ae5e6d537e15e94054fe6a',
    messagingSenderId: '769280217055',
    projectId: 'safe-return2',
    storageBucket: 'safe-return2.appspot.com',
    iosBundleId: 'com.example.safeReturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIrjMlcNJgEBurd2YawSKnU_CxkeSY-JE',
    appId: '1:769280217055:web:ee37c4cebfa4ef6d54fe6a',
    messagingSenderId: '769280217055',
    projectId: 'safe-return2',
    authDomain: 'safe-return2.firebaseapp.com',
    storageBucket: 'safe-return2.appspot.com',
    measurementId: 'G-72LG00Z9DS',
  );

}