// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmrEqksBOTumI6EjY0lsw4tfUU5NVhbE',
    appId: '1:1099191218085:web:c810e21256340fdd1f424c',
    messagingSenderId: '1099191218085',
    projectId: 'testnotifications-a13fd',
    authDomain: 'testnotifications-a13fd.firebaseapp.com',
    storageBucket: 'testnotifications-a13fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAekJdyC8osOLwCF9xzlmPaUoxMHO9lsIo',
    appId: '1:1099191218085:android:1dda2cc855aac5f51f424c',
    messagingSenderId: '1099191218085',
    projectId: 'testnotifications-a13fd',
    storageBucket: 'testnotifications-a13fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRvFL35kXg3J7RUp6POiV0cksXgNAL74o',
    appId: '1:1099191218085:ios:1d649cc55f6220e21f424c',
    messagingSenderId: '1099191218085',
    projectId: 'testnotifications-a13fd',
    storageBucket: 'testnotifications-a13fd.appspot.com',
    iosBundleId: 'com.example.safeReturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRvFL35kXg3J7RUp6POiV0cksXgNAL74o',
    appId: '1:1099191218085:ios:1d649cc55f6220e21f424c',
    messagingSenderId: '1099191218085',
    projectId: 'testnotifications-a13fd',
    storageBucket: 'testnotifications-a13fd.appspot.com',
    iosBundleId: 'com.example.safeReturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGmrEqksBOTumI6EjY0lsw4tfUU5NVhbE',
    appId: '1:1099191218085:web:3a71f658d8e0aaf51f424c',
    messagingSenderId: '1099191218085',
    projectId: 'testnotifications-a13fd',
    authDomain: 'testnotifications-a13fd.firebaseapp.com',
    storageBucket: 'testnotifications-a13fd.appspot.com',
  );

}