// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuGzPGInVRKtML-CAHKPVoAtKK67FaTGE',
    appId: '1:413813114386:web:95a580d6fce72add06bacb',
    messagingSenderId: '413813114386',
    projectId: 'safe-return-b4cbe',
    authDomain: 'safe-return-b4cbe.firebaseapp.com',
    storageBucket: 'safe-return-b4cbe.appspot.com',
    measurementId: 'G-ZW7NJK1096',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFUQ9zrLFJAVbcHPsLQ3iPt_Pvnh1-FDo',
    appId: '1:413813114386:android:d88bb17a3715406606bacb',
    messagingSenderId: '413813114386',
    projectId: 'safe-return-b4cbe',
    storageBucket: 'safe-return-b4cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIa5YCaC8dGgf5Cv2E2WtCm8nwuIxlCn0',
    appId: '1:413813114386:ios:a5d675853b50718506bacb',
    messagingSenderId: '413813114386',
    projectId: 'safe-return-b4cbe',
    storageBucket: 'safe-return-b4cbe.appspot.com',
    iosBundleId: 'com.example.safeReturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIa5YCaC8dGgf5Cv2E2WtCm8nwuIxlCn0',
    appId: '1:413813114386:ios:a5d675853b50718506bacb',
    messagingSenderId: '413813114386',
    projectId: 'safe-return-b4cbe',
    storageBucket: 'safe-return-b4cbe.appspot.com',
    iosBundleId: 'com.example.safeReturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuGzPGInVRKtML-CAHKPVoAtKK67FaTGE',
    appId: '1:413813114386:web:f02f61d74946801906bacb',
    messagingSenderId: '413813114386',
    projectId: 'safe-return-b4cbe',
    authDomain: 'safe-return-b4cbe.firebaseapp.com',
    storageBucket: 'safe-return-b4cbe.appspot.com',
    measurementId: 'G-22CSLTC1F7',
  );

}